import type { GraphDoc } from '../editor/model';

/**
 * Catálogo del Marketplace (M75) — la «App Store» de empleados digitales: AI Teams, Agents, Automations,
 * Browser Automation y MCP Solutions. Es data RICA en el front (como las plantillas, pero con toda la
 * metadata + una RECETA de instalación). Instalar usa las APIs existentes: crea los agentes y el workflow,
 * y detecta los conectores que faltan. rating/installs son de vitrina; el resto es real.
 */

export type MarketKind = 'team' | 'agent' | 'automation' | 'browser' | 'mcp';

/** Un agente de la receta: se crea al instalar y se referencia en el grafo por `ref`. */
export interface SeedAgent {
  ref: string;
  name: string;
  emoji: string;
  role: string;
  systemPrompt: string;
  model: string;
  tools: string[];
  mcpServers?: { name: string; url: string }[];
  isOrchestrator?: boolean;
}

/** Qué crea la instalación: agentes (opcional) y/o un workflow ya cableado. */
export interface InstallRecipe {
  agents?: SeedAgent[];
  workflow?: { name: string; doc: GraphDoc };
}

export interface MarketVariable {
  key: string;
  label: string;
  example?: string;
}

export interface MarketItem {
  id: string;
  kind: MarketKind;
  name: string;
  tagline: string;
  description: string;
  icon: string;
  gradient: string;
  category: string; // área de negocio
  difficulty: 'Fácil' | 'Media' | 'Avanzada';
  setupMinutes: number;
  connectors: string[]; // claves de proveedor
  mcps: string[];
  tools: string[];
  useCases: string[];
  variables?: MarketVariable[];
  requirements?: string[];
  rating: number;
  installs: number;
  author: string;
  badges: string[];
  collections: string[];
  install: InstallRecipe;
}

/** Categorías de primer nivel (los «niveles» del marketplace). */
export const KINDS: { key: MarketKind; label: string; icon: string; tagline: string }[] = [
  { key: 'team', label: 'AI Teams', icon: '🤝', tagline: 'Equipos de agentes que colaboran' },
  { key: 'agent', label: 'AI Agents', icon: '🤖', tagline: 'Empleados digitales individuales' },
  { key: 'automation', label: 'Automations', icon: '⚡', tagline: 'Flujos entre tus apps' },
  { key: 'browser', label: 'Browser Automation', icon: '🌐', tagline: 'Tareas en el navegador' },
  { key: 'mcp', label: 'MCP Solutions', icon: '🧩', tagline: 'Expertos conectados por MCP' },
];

/** Colecciones destacadas (chips de la home del marketplace). */
export const COLLECTIONS: { id: string; label: string; emoji: string }[] = [
  { id: 'popular', label: 'Most Popular', emoji: '🔥' },
  { id: 'new', label: 'New', emoji: '✨' },
  { id: 'trending', label: 'Trending', emoji: '📈' },
  { id: 'ai-teams', label: 'AI Teams', emoji: '🤝' },
  { id: 'beginner', label: 'Beginner Friendly', emoji: '🌱' },
  { id: 'browser', label: 'Browser Automation', emoji: '🌐' },
  { id: 'mcp', label: 'MCP Ready', emoji: '🧩' },
];

// --- Helpers para construir los grafos de instalación (mismo formato que las plantillas) ---
type N = GraphDoc['nodes'][number];
const node = (id: string, kind: string, x: number, y: number, config: Record<string, unknown> = {}): N =>
  ({ id, kind, position: { x, y }, config }) as N;
const edge = (source: string, target: string, sourceHandle?: string) => ({
  id: `e_${source}_${target}${sourceHandle ? `_${sourceHandle}` : ''}`,
  source,
  target,
  sourceHandle: sourceHandle ?? null,
});
const M = 'gpt-4o-mini';

export const MARKETPLACE: MarketItem[] = [
  // ------------------------------- ATLASSIAN (M76) ------------------------------
  // Integración de primera clase: la plataforma es dueña del OAuth; al instalar, si Atlassian no está
  // conectado, el asistente lo pide (una vez) y los agentes usan Jira/Confluence como herramientas.
  {
    id: 'atlassian-project-assistant',
    kind: 'agent',
    name: 'Atlassian Project Assistant',
    tagline: 'Gestiona Jira y Confluence en tu idioma: busca, crea y actualiza sin tocar la API.',
    description:
      'Un empleado digital conectado a tu Atlassian. Encuentra incidencias con lenguaje natural, crea tickets, comenta, cambia estados y gestiona documentación en Confluence. La plataforma gestiona el acceso (OAuth): el agente nunca ve credenciales.',
    icon: '🧩',
    gradient: 'from-blue-500/25 to-indigo-500/25',
    category: 'Producto e Ingeniería',
    difficulty: 'Fácil',
    setupMinutes: 2,
    connectors: ['jira'],
    mcps: [],
    tools: [],
    useCases: ['«Crea un bug en KAN: el login falla en Safari»', 'Resume las incidencias abiertas del sprint', 'Crea una página de retro en Confluence'],
    requirements: ['Una cuenta de Atlassian (Jira o Confluence)'],
    rating: 4.8,
    installs: 0,
    author: 'Workestra',
    badges: ['Oficial'],
    collections: ['new', 'popular'],
    install: {
      agents: [
        {
          ref: 'assistant',
          name: 'Atlassian Assistant',
          emoji: '🧩',
          role: 'Asistente de Atlassian',
          model: M,
          tools: [],
          mcpServers: [{ name: 'Atlassian', url: 'integration://atlassian' }],
          systemPrompt:
            'Eres un asistente experto en Atlassian. Usa las herramientas de Jira y Confluence para cumplir la petición: buscar/crear/actualizar incidencias y páginas. Confirma lo hecho con la clave o el título del recurso. Si falta un dato (proyecto, espacio), pregúntalo antes de actuar.',
        },
      ],
    },
  },
  {
    id: 'sprint-ops-atlassian',
    kind: 'team',
    name: 'Sprint Ops (Jira + Confluence)',
    tagline: 'Un equipo que triaja peticiones, crea las incidencias en Jira y documenta el resultado en Confluence.',
    description:
      'Tres agentes que comparten UNA conexión de Atlassian: un coordinador decide qué hacer, un especialista de Jira crea o actualiza las incidencias y un documentalista deja la página en Confluence. Instálalo y conecta Atlassian una vez; todos lo usan.',
    icon: '🏃',
    gradient: 'from-sky-500/25 to-blue-600/25',
    category: 'Producto e Ingeniería',
    difficulty: 'Media',
    setupMinutes: 3,
    connectors: ['jira'],
    mcps: [],
    tools: [],
    useCases: ['Convertir una petición en un ticket de Jira y su doc en Confluence', 'Triaje de incidencias entrantes', 'Cerrar el sprint documentando lo entregado'],
    requirements: ['Una cuenta de Atlassian (Jira y Confluence)'],
    rating: 4.7,
    installs: 0,
    author: 'Workestra',
    badges: ['Oficial'],
    collections: ['new', 'ai-teams'],
    install: {
      agents: [
        { ref: 'lead', name: 'Team Lead', emoji: '🧭', role: 'Triages requests and routes to specialists', model: M, tools: [], isOrchestrator: true, systemPrompt: 'Eres el Team Lead de un equipo de Sprint Ops sobre Atlassian. Lee la petición entrante y decide qué especialista o especialistas deben actuar: analista (triaje y alcance), Jira (crear o actualizar incidencias), Confluence (documentar el resultado) o QA (criterios de aceptación y regresiones). Elige solo los necesarios y reparte el trabajo con instrucciones claras y breves.' },
        { ref: 'analyst', name: 'Product Analyst', emoji: '🔎', role: 'Triages and scopes the request', model: M, tools: [], systemPrompt: 'Eres analista de producto. A partir de la petición, aclara el objetivo, define el alcance y desglosa el trabajo en tareas accionables. Señala dependencias, riesgos y qué información falta para avanzar.' },
        { ref: 'jira', name: 'Jira Specialist', emoji: '📋', role: 'Creates and updates Jira issues', model: M, tools: [], mcpServers: [{ name: 'Atlassian', url: 'integration://atlassian' }], systemPrompt: 'Eres especialista de Jira. Usa las herramientas de Atlassian para crear, buscar y actualizar las incidencias que requiera la petición, con título, descripción y etiquetas adecuadas. Devuelve la clave de cada incidencia (p. ej. KAN-12).' },
        { ref: 'docs', name: 'Confluence Documenter', emoji: '📚', role: 'Documents the outcome in Confluence', model: M, tools: [], mcpServers: [{ name: 'Atlassian', url: 'integration://atlassian' }], systemPrompt: 'Eres documentalista de Confluence. Usa las herramientas de Atlassian para crear o actualizar la página que documenta la petición y su resultado, con contexto, decisiones y enlaces a las incidencias. Devuelve el título y el enlace de la página.' },
        { ref: 'qa', name: 'QA Engineer', emoji: '🧪', role: 'Defines acceptance criteria and test plan', model: M, tools: [], systemPrompt: 'Eres ingeniero de QA. A partir de la petición, define los criterios de aceptación, los casos de prueba happy-path y borde, y las regresiones a vigilar. Sé concreto para que el equipo pueda validar el trabajo entregado.' },
      ],
      workflow: {
        name: 'Sprint Ops (Jira + Confluence)',
        doc: {
          nodes: [
            node('trigger', 'trigger', 40, 285, { event: 'webhook', eventId: 'jira.issue_created' }),
            node('lead', 'router', 340, 285, { agentRef: 'lead', input: 'Reparte esta petición de sprint al especialista o especialistas más adecuados según su contenido: si hay que crear o actualizar una incidencia usa Jira, si hay que dejar constancia usa Confluence, y si hay que definir criterios de aceptación usa QA. Petición:\n{{ticket.key}} — {{ticket.summary}}\n{{ticket.description}}' }),
            node('analyst', 'agent', 640, 60, { agentRef: 'analyst', input: 'Triajea y define el alcance de esta petición, con tareas y dependencias claras:\n{{ticket.key}} — {{ticket.summary}}\n{{ticket.description}}' }),
            node('jira', 'agent', 640, 210, { agentRef: 'jira', input: 'Crea o actualiza las incidencias de Jira necesarias para:\n{{ticket.key}} — {{ticket.summary}}\n{{ticket.description}}' }),
            node('docs', 'agent', 640, 360, { agentRef: 'docs', input: 'Documenta en Confluence el contexto y el resultado de:\n{{ticket.key}} — {{ticket.summary}}\n{{ticket.description}}' }),
            node('qa', 'agent', 640, 510, { agentRef: 'qa', input: 'Define los criterios de aceptación y el plan de pruebas para:\n{{ticket.key}} — {{ticket.summary}}\n{{ticket.description}}' }),
            node('end', 'end', 940, 285, {}),
          ],
          edges: [
            edge('trigger', 'lead'),
            edge('lead', 'analyst'),
            edge('lead', 'jira'),
            edge('lead', 'docs'),
            edge('lead', 'qa'),
            edge('analyst', 'end'),
            edge('jira', 'end'),
            edge('docs', 'end'),
            edge('qa', 'end'),
          ],
          comments: [],
        },
      },
    },
  },

  // ---------------------------------- AI TEAMS ----------------------------------
  {
    id: 'team-customer-support',
    kind: 'team',
    name: 'Customer Support Team',
    tagline: 'Triaje, respuesta y escalado de tickets, en equipo.',
    description:
      'Un equipo completo de atención al cliente: un coordinador clasifica cada consulta, un agente de soporte redacta la respuesta con tono de marca, y si el caso es delicado se avisa a tu equipo por Slack. Ideal para bandeja de entrada de soporte o formularios de contacto.',
    icon: '🎧',
    gradient: 'from-sky-500 to-indigo-500',
    category: 'Customer Support',
    difficulty: 'Media',
    setupMinutes: 8,
    connectors: ['gmail', 'slack'],
    mcps: [],
    tools: ['http'],
    useCases: ['Bandeja de soporte', 'Formularios de contacto', 'Chat de ayuda'],
    variables: [{ key: 'brand', label: 'Nombre de tu marca', example: 'ACME' }],
    requirements: ['Una cuenta de Gmail o correo de soporte', 'Un canal de Slack para escalados'],
    rating: 4.9,
    installs: 3820,
    author: 'workestra',
    badges: ['Popular', 'AI Powered'],
    collections: ['popular', 'ai-teams', 'trending'],
    install: {
      agents: [
        { ref: 'lead', name: 'Support Team Lead', emoji: '🧭', role: 'Triages tickets and routes to the right specialist', model: M, tools: [], isOrchestrator: true, systemPrompt: 'Eres el Team Lead de un equipo de atención al cliente. Lee cada ticket entrante y clasifícalo por tema y prioridad: facturación, técnico, comercial o retención. Decide qué especialista(s) deben ocuparse y reparte el trabajo con instrucciones claras; si el caso es delicado o el cliente amenaza con irse, activa también al especialista de retención. Sé breve y elige solo los agentes necesarios.' },
        { ref: 'billing', name: 'Billing Specialist', emoji: '💳', role: 'Handles invoices, charges and refunds', model: M, tools: [], systemPrompt: 'Eres un especialista en facturación de soporte. Analiza el ticket sobre cargos, facturas, reembolsos o cambios de plan y redacta una respuesta clara y empática para el cliente. Explica los pasos concretos y, si necesitas datos internos, indica exactamente qué consultar antes de enviar.' },
        { ref: 'technical', name: 'Technical Support Agent', emoji: '🛠️', role: 'Troubleshoots product and technical issues', model: M, tools: [], systemPrompt: 'Eres un agente de soporte técnico resolutivo. A partir del ticket, diagnostica el problema, ofrece pasos de solución claros y numerados, y pide solo la información imprescindible que falte. Si el problema parece un bug o requiere ingeniería, márcalo para escalado con un resumen técnico conciso.' },
        { ref: 'responder', name: 'Customer Response Writer', emoji: '💬', role: 'Writes the branded customer-facing reply', model: M, tools: [], systemPrompt: 'Eres el redactor de respuestas al cliente. Toma el diagnóstico del especialista y conviértelo en un mensaje final claro, empático y con el tono de la marca. Sé cálido y directo, confirma el siguiente paso y ofrece escalar si el cliente sigue sin quedar satisfecho.' },
        { ref: 'retention', name: 'Retention Specialist', emoji: '🤝', role: 'Handles complaints, escalations and churn risk', model: M, tools: [], systemPrompt: 'Eres un especialista en retención y casos delicados. Cuando el cliente está molesto, amenaza con irse o presenta una queja seria, redacta una respuesta que reconozca el problema, ofrezca una solución o compensación razonable y recupere la confianza. Marca el caso como urgente para que el equipo lo revise por Slack.' },
      ],
      workflow: {
        name: 'Customer Support Team',
        doc: {
          nodes: [
            node('trigger', 'trigger', 40, 285, { event: 'webhook' }),
            node('lead', 'router', 340, 285, { agentRef: 'lead', input: 'Clasifica y asigna este ticket de soporte al especialista más adecuado según su tema y prioridad:\\n{{ticket.key}} — {{ticket.summary}}\\n{{ticket.description}}' }),
            node('billing', 'agent', 640, 60, { agentRef: 'billing', input: 'Resuelve y redacta la respuesta de facturación para este ticket:\n{{ticket.key}} — {{ticket.summary}}\n{{ticket.description}}' }),
            node('technical', 'agent', 640, 210, { agentRef: 'technical', input: 'Diagnostica y redacta la respuesta técnica para este ticket:\n{{ticket.key}} — {{ticket.summary}}\n{{ticket.description}}' }),
            node('responder', 'agent', 640, 360, { agentRef: 'responder', input: 'Redacta la respuesta final al cliente con tono de marca sobre:\n{{ticket.key}} — {{ticket.summary}}\n{{ticket.description}}' }),
            node('retention', 'agent', 640, 510, { agentRef: 'retention', input: 'Gestiona este caso delicado o de riesgo de fuga y propón una respuesta de retención:\n{{ticket.key}} — {{ticket.summary}}\n{{ticket.description}}' }),
            node('end', 'end', 940, 285, {}),
          ],
          edges: [
            edge('trigger', 'lead'),
            edge('lead', 'billing'),
            edge('lead', 'technical'),
            edge('lead', 'responder'),
            edge('lead', 'retention'),
            edge('billing', 'end'),
            edge('technical', 'end'),
            edge('responder', 'end'),
            edge('retention', 'end'),
          ],
          comments: [],
        },
      },
    },
  },
  {
    id: 'team-sales',
    kind: 'team',
    name: 'Sales Team',
    tagline: 'Califica leads, redacta el primer contacto y avisa a ventas.',
    description:
      'Equipo comercial que recibe un lead, lo califica (BANT), redacta un email de primer contacto personalizado y notifica al comercial asignado. Conecta tu CRM para registrar la actividad.',
    icon: '💼',
    gradient: 'from-emerald-500 to-lime-500',
    category: 'Sales',
    difficulty: 'Media',
    setupMinutes: 10,
    connectors: ['hubspot', 'gmail'],
    mcps: [],
    tools: ['http'],
    useCases: ['Inbound leads', 'Formularios de demo', 'Enriquecer y priorizar'],
    rating: 4.8,
    installs: 2610,
    author: 'workestra',
    badges: ['Popular', 'Sales Automation'],
    collections: ['popular', 'ai-teams', 'trending'],
    install: {
      agents: [
        { ref: 'lead', name: 'Sales Team Lead', emoji: '🧑‍✈️', role: 'Routes the incoming lead to the right specialist(s)', model: M, tools: [], isOrchestrator: true, systemPrompt: 'Eres el Team Lead de un equipo comercial. Lee el lead entrante ({{ticket.summary}} y {{ticket.description}}) y decide qué especialista(s) deben ocuparse: calificación BANT, enriquecimiento e investigación de la cuenta, redacción del primer email o coordinación con el CRM. Elige solo los necesarios y reparte el trabajo con instrucciones claras y accionables.' },
        { ref: 'qualifier', name: 'Lead Qualifier', emoji: '🎯', role: 'Scores the lead with BANT', model: M, tools: [], systemPrompt: 'Eres un SDR especializado en calificación. Analiza el lead y puntúalo con BANT (presupuesto, autoridad, necesidad y plazo), asignando una nota de 1 a 5 con una frase de justificación por cada dimensión. Termina con una recomendación clara: priorizar, nutrir o descartar.' },
        { ref: 'researcher', name: 'Lead Researcher', emoji: '🔎', role: 'Enriches and researches the account', model: M, tools: [], systemPrompt: 'Eres un analista de inteligencia comercial. Enriquece el lead investigando la empresa y el contacto: sector, tamaño, señales de compra y posibles puntos de dolor. Resume en 4-6 hallazgos concretos que ayuden a personalizar el primer contacto.' },
        { ref: 'writer', name: 'Outreach Writer', emoji: '✍️', role: 'Writes the personalized first-contact email', model: M, tools: [], systemPrompt: 'Eres un redactor de ventas. Escribe un primer email breve, personalizado y humano, apoyándote en la calificación y el enriquecimiento disponibles. Incluye una llamada a la acción clara (agendar una demo) y evita cualquier tono de spam.' },
        { ref: 'crm', name: 'CRM Coordinator', emoji: '🗂️', role: 'Logs activity and notifies the sales rep', model: M, tools: [], systemPrompt: 'Eres el responsable de operaciones de ventas. Prepara el resumen de la actividad para registrar en el CRM (calificación, hallazgos clave y siguiente paso) y redacta una notificación breve para el comercial asignado con la prioridad del lead y la acción recomendada.' },
      ],
      workflow: {
        name: 'Sales Team',
        doc: {
          nodes: [
            node('trigger', 'trigger', 40, 285, { event: 'webhook' }),
            node('lead', 'router', 340, 285, { agentRef: 'lead', input: 'Reparte este lead entrante al especialista o especialistas más adecuados (calificación BANT, enriquecimiento e investigación, redacción del primer contacto o coordinación con el CRM):\n{{ticket.key}} — {{ticket.summary}}\n{{ticket.description}}' }),
            node('qualifier', 'agent', 640, 60, { agentRef: 'qualifier', input: 'Califica este lead con BANT y da una puntuación de 1 a 5 con justificación:\n{{ticket.key}} — {{ticket.summary}}\n{{ticket.description}}' }),
            node('researcher', 'agent', 640, 210, { agentRef: 'researcher', input: 'Investiga y enriquece este lead con contexto de empresa, sector y posibles necesidades:\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('writer', 'agent', 640, 360, { agentRef: 'writer', input: 'Escribe el primer email de contacto, personalizado y con una llamada a la acción clara, para:\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('crm', 'agent', 640, 510, { agentRef: 'crm', input: 'Prepara el registro de actividad en el CRM y la notificación al comercial asignado para este lead:\n{{ticket.key}} — {{ticket.summary}}\n{{ticket.description}}' }),
            node('end', 'end', 940, 285, {}),
          ],
          edges: [
            edge('trigger', 'lead'),
            edge('lead', 'qualifier'),
            edge('lead', 'researcher'),
            edge('lead', 'writer'),
            edge('lead', 'crm'),
            edge('qualifier', 'end'),
            edge('researcher', 'end'),
            edge('writer', 'end'),
            edge('crm', 'end'),
          ],
          comments: [],
        },
      },
    },
  },
  {
    id: 'team-recruiting',
    kind: 'team',
    name: 'Recruiting Team',
    tagline: 'Cribado de CVs, resumen y propuesta de entrevista.',
    description:
      'Equipo de selección: revisa una candidatura frente a la oferta, resume fortalezas y riesgos, y prepara un email para agendar (o descartar con tacto). Conecta tu calendario para proponer huecos.',
    icon: '🧑‍💼',
    gradient: 'from-violet-500 to-purple-500',
    category: 'HR',
    difficulty: 'Media',
    setupMinutes: 9,
    connectors: ['gmail', 'google-calendar'],
    mcps: [],
    tools: [],
    useCases: ['Cribado de candidatos', 'Screening inicial', 'Agenda de entrevistas'],
    rating: 4.7,
    installs: 1440,
    author: 'workestra',
    badges: ['New', 'AI Powered'],
    collections: ['new', 'ai-teams'],
    install: {
      agents: [
        { ref: 'lead', name: 'Recruiting Lead', emoji: '🧑‍✈️', role: 'Routes each candidacy to the right specialist(s)', model: M, tools: [], isOrchestrator: true, systemPrompt: 'Eres el responsable del equipo de selección. Lee la candidatura y la oferta e identifica qué se necesita: cribado de encaje, verificación de referencias/experiencia, redacción de comunicación al candidato o propuesta de agenda de entrevista. Decide qué especialista(s) deben actuar y repárteles el trabajo con instrucciones claras, eligiendo solo los necesarios.' },
        { ref: 'screener', name: 'CV Screener', emoji: '🔎', role: 'Evaluates candidate fit against the role', model: M, tools: [], systemPrompt: 'Eres un reclutador técnico. Evalúa la candidatura frente a la oferta y devuelve un encaje del 1 al 5, las fortalezas, los riesgos y una recomendación clara de avanzar o descartar. Sé objetivo y justifica cada punto con evidencia de la candidatura.' },
        { ref: 'sourcer', name: 'Background Analyst', emoji: '🧭', role: 'Verifies experience, gaps and references', model: M, tools: [], systemPrompt: 'Eres analista de antecedentes de RRHH. Revisa el historial del candidato: valida coherencia de experiencia, detecta huecos o banderas rojas y sugiere preguntas de verificación de referencias. Sé preciso y evita suposiciones sin base.' },
        { ref: 'comms', name: 'Candidate Communications', emoji: '✉️', role: 'Drafts respectful candidate emails', model: M, tools: [], systemPrompt: 'Redactas comunicaciones de RRHH con tacto y claridad. Si el candidato avanza, prepara un email cordial invitándole a la siguiente fase; si se descarta, agradece con respeto y deja la puerta abierta. Adapta el tono al idioma del candidato.' },
        { ref: 'scheduler', name: 'Interview Scheduler', emoji: '📅', role: 'Proposes interview slots and logistics', model: M, tools: [], systemPrompt: 'Eres coordinador de entrevistas. Propón dos o tres huecos concretos para la entrevista, indica el formato (video o presencial) y los participantes, y prepara un resumen de logística claro para confirmar con el candidato. Sé práctico y explícito con fechas y duración.' },
      ],
      workflow: {
        name: 'Recruiting Team',
        doc: {
          nodes: [
            node('trigger', 'trigger', 40, 285, { event: 'manual' }),
            node('lead', 'router', 340, 285, { agentRef: 'lead', input: 'Reparte esta candidatura al especialista o especialistas más adecuados del equipo de selección:\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('screener', 'agent', 640, 60, { agentRef: 'screener', input: 'Evalúa el encaje de esta candidatura frente a la oferta y da recomendación:\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('sourcer', 'agent', 640, 210, { agentRef: 'sourcer', input: 'Analiza el historial y posibles banderas rojas del candidato:\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('comms', 'agent', 640, 360, { agentRef: 'comms', input: 'Redacta el email al candidato según la decisión del equipo:\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('scheduler', 'agent', 640, 510, { agentRef: 'scheduler', input: 'Propón huecos y logística de entrevista para este candidato:\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('end', 'end', 940, 285, {}),
          ],
          edges: [
            edge('trigger', 'lead'),
            edge('lead', 'screener'),
            edge('lead', 'sourcer'),
            edge('lead', 'comms'),
            edge('lead', 'scheduler'),
            edge('screener', 'end'),
            edge('sourcer', 'end'),
            edge('comms', 'end'),
            edge('scheduler', 'end'),
          ],
          comments: [],
        },
      },
    },
  },
  {
    id: 'team-research',
    kind: 'team',
    name: 'Research Team',
    tagline: 'Investiga en la web, analiza y redacta un informe.',
    description:
      'Equipo de investigación: un agente busca y navega la web, un analista extrae los hechos clave y un redactor produce un informe claro con fuentes. Perfecto para due diligence, análisis de mercado o competencia.',
    icon: '🔬',
    gradient: 'from-amber-500 to-orange-500',
    category: 'Research',
    difficulty: 'Avanzada',
    setupMinutes: 6,
    connectors: [],
    mcps: [],
    tools: ['browser', 'http'],
    useCases: ['Análisis de mercado', 'Investigación de competencia', 'Due diligence'],
    rating: 4.8,
    installs: 2050,
    author: 'workestra',
    badges: ['Trending', 'AI Powered'],
    collections: ['trending', 'ai-teams'],
    install: {
      agents: [
        { ref: 'lead', name: 'Research Lead', emoji: '🧭', role: 'Routes the topic to the right specialists', model: M, tools: [], isOrchestrator: true, systemPrompt: 'Eres el Research Lead de un equipo de investigación. Lee el tema o la pregunta de entrada y decide qué especialista(s) deben intervenir: investigación web, análisis de hallazgos, verificación de datos o redacción del informe. Elige solo los necesarios según lo que pida el usuario y reparte el trabajo con instrucciones claras y el alcance esperado.' },
        { ref: 'researcher', name: 'Web Researcher', emoji: '🌐', role: 'Searches and browses the web for sources', model: M, tools: [], systemPrompt: 'Eres un investigador web. Usa el navegador y HTTP para reunir información fiable y actual sobre el tema. Prioriza fuentes primarias y citables, y devuelve siempre las URLs junto a cada hallazgo. Sé riguroso y evita conclusiones no respaldadas.' },
        { ref: 'analyst', name: 'Data Analyst', emoji: '📊', role: 'Extracts key facts and implications', model: M, tools: [], systemPrompt: 'Eres un analista. A partir de la investigación reunida, extrae los 5-7 hechos más relevantes, sus implicaciones y las tendencias o patrones que aparezcan. Estructura la salida de forma clara y señala los vacíos de información que aún falten por cubrir.' },
        { ref: 'factcheck', name: 'Fact Checker', emoji: '🔎', role: 'Verifies claims against sources', model: M, tools: [], systemPrompt: 'Eres un verificador de datos. Contrasta cada afirmación clave contra sus fuentes y marca cada una como confirmada, dudosa o no respaldada. Detecta contradicciones entre fuentes y sesgos, y recomienda qué afirmaciones necesitan una fuente adicional antes de publicarse.' },
        { ref: 'writer', name: 'Report Writer', emoji: '📝', role: 'Writes the final report with sources', model: M, tools: [], systemPrompt: 'Eres un redactor. Produce un informe ejecutivo claro y conciso, con secciones, hallazgos principales y una conclusión accionable. Cita las fuentes (URLs) de cada afirmación relevante y mantén un tono profesional y neutral.' },
      ],
      workflow: {
        name: 'Research Team',
        doc: {
          nodes: [
            node('trigger', 'trigger', 40, 285, { event: 'manual' }),
            node('lead', 'router', 340, 285, { agentRef: 'lead', input: 'Analiza esta petición de investigación y asígnala al especialista o especialistas más adecuados (investigación web, análisis, verificación de datos o redacción):\\n{{ticket.summary}}\\n{{ticket.description}}' }),
            node('researcher', 'agent', 640, 60, { agentRef: 'researcher', input: 'Investiga a fondo este tema y reúne hallazgos con sus fuentes (URLs):\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('analyst', 'agent', 640, 210, { agentRef: 'analyst', input: 'Analiza estos hallazgos y extrae los hechos clave, implicaciones y vacíos de información:\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('factcheck', 'agent', 640, 360, { agentRef: 'factcheck', input: 'Verifica las afirmaciones clave contra sus fuentes y marca cada una como confirmada, dudosa o no respaldada:\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('writer', 'agent', 640, 510, { agentRef: 'writer', input: 'Redacta el informe ejecutivo final con secciones, conclusión y fuentes citadas, a partir del tema:\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('end', 'end', 940, 285, {}),
          ],
          edges: [
            edge('trigger', 'lead'),
            edge('lead', 'researcher'),
            edge('lead', 'analyst'),
            edge('lead', 'factcheck'),
            edge('lead', 'writer'),
            edge('researcher', 'end'),
            edge('analyst', 'end'),
            edge('factcheck', 'end'),
            edge('writer', 'end'),
          ],
          comments: [],
        },
      },
    },
  },

  {
    id: 'team-dev',
    kind: 'team',
    name: 'Dev Team',
    tagline: 'Un ticket de Jira lo reparte el Team Lead entre tus developers.',
    description:
      'Un equipo de desarrollo que arranca solo cuando entra un ticket en Jira. Un Team Lead (router) lee el ticket, decide a qué especialista le toca — frontend, backend o QA — y le pasa el trabajo; pueden entrar varios a la vez si el ticket lo requiere. Cada developer devuelve su plan de implementación. Ideal para triaje y arranque automático de tareas de ingeniería.',
    icon: '👩‍💻',
    gradient: 'from-violet-500 to-fuchsia-500',
    category: 'Engineering',
    difficulty: 'Media',
    setupMinutes: 7,
    connectors: ['jira'],
    mcps: [],
    tools: ['http'],
    useCases: ['Triaje de tickets de ingeniería', 'Arranque automático de tareas', 'Reparto de trabajo por especialidad'],
    requirements: ['Una cuenta de Jira con el disparador de tickets activado'],
    rating: 4.8,
    installs: 1460,
    author: 'workestra',
    badges: ['New', 'AI Powered'],
    collections: ['new', 'ai-teams', 'trending'],
    install: {
      agents: [
        { ref: 'lead', name: 'Team Lead', emoji: '🧑‍✈️', role: 'Reparte el ticket', model: M, tools: [], isOrchestrator: true, systemPrompt: 'Eres el Team Lead de un equipo de desarrollo. Lee el ticket de Jira y decide qué especialista(s) deben ocuparse: frontend (UI, componentes), backend (API, datos, lógica) o QA (pruebas, regresiones). Elige solo los necesarios y reparte el trabajo con instrucciones claras.' },
        { ref: 'frontend', name: 'Frontend Developer', emoji: '🎨', role: 'Solo interfaz: UI, componentes y estilos', model: M, tools: [], systemPrompt: 'Eres un desarrollador frontend. A partir del ticket, propón el plan de implementación de UI: componentes, estados, llamadas a la API y casos borde. Sé concreto y accionable.' },
        { ref: 'backend', name: 'Backend Developer', emoji: '⚙️', role: 'Solo servidor: API, base de datos y lógica', model: M, tools: [], systemPrompt: 'Eres un desarrollador backend. A partir del ticket, propón el plan de implementación: endpoints, modelo de datos, validaciones y migraciones. Señala riesgos y dependencias.' },
        { ref: 'qa', name: 'QA Engineer', emoji: '🧪', role: 'Solo pruebas: QA, criterios y regresiones', model: M, tools: [], systemPrompt: 'Eres ingeniero de QA. A partir del ticket, define el plan de pruebas: criterios de aceptación, casos happy-path y borde, y regresiones a vigilar.' },
      ],
      workflow: {
        name: 'Dev Team',
        doc: {
          nodes: [
            node('trigger', 'trigger', 40, 220, { event: 'webhook', eventId: 'jira.issue_created' }),
            node('lead', 'router', 320, 220, { agentRef: 'lead', input: 'Asigna este ticket de Jira al ÚNICO especialista más adecuado (frontend, backend o QA):\n{{ticket.key}} — {{ticket.summary}}\n{{ticket.description}}', max: 1 }),
            node('frontend', 'agent', 620, 60, { agentRef: 'frontend', input: 'Plan de implementación frontend para:\n{{ticket.key}} — {{ticket.summary}}\n{{ticket.description}}' }),
            node('backend', 'agent', 620, 220, { agentRef: 'backend', input: 'Plan de implementación backend para:\n{{ticket.key}} — {{ticket.summary}}\n{{ticket.description}}' }),
            node('qa', 'agent', 620, 380, { agentRef: 'qa', input: 'Plan de pruebas para:\n{{ticket.key}} — {{ticket.summary}}\n{{ticket.description}}' }),
            node('end', 'end', 920, 220, {}),
          ],
          edges: [
            edge('trigger', 'lead'),
            edge('lead', 'frontend'),
            edge('lead', 'backend'),
            edge('lead', 'qa'),
            edge('frontend', 'end'),
            edge('backend', 'end'),
            edge('qa', 'end'),
          ],
          comments: [],
        },
      },
    },
  },

  // ---------------------------------- AI AGENTS ----------------------------------
  {
    id: 'agent-email-assistant',
    kind: 'agent',
    name: 'Email Assistant',
    tagline: 'Lee, resume y redacta respuestas de correo.',
    description: 'Un asistente que entiende un hilo de correo, lo resume y propone una respuesta lista para enviar, con tu tono. Conecta Gmail para enviar directamente.',
    icon: '📧',
    gradient: 'from-rose-500 to-red-500',
    category: 'Operations',
    difficulty: 'Fácil',
    setupMinutes: 4,
    connectors: ['gmail'],
    mcps: [],
    tools: [],
    useCases: ['Bandeja de entrada', 'Respuestas rápidas', 'Resúmenes de hilos'],
    rating: 4.9,
    installs: 8900,
    author: 'workestra',
    badges: ['Popular', 'Beginner Friendly'],
    collections: ['popular', 'beginner'],
    install: {
      agents: [{ ref: 'a', name: 'Email Assistant', emoji: '📧', role: 'Correo', model: M, tools: [], systemPrompt: 'Eres un asistente de correo. Resume el hilo y propón una respuesta clara, educada y accionable, en el idioma del remitente.' }],
    },
  },
  {
    id: 'agent-research',
    kind: 'agent',
    name: 'Research Agent',
    tagline: 'Investiga cualquier tema navegando la web.',
    description: 'Un investigador que navega, busca y sintetiza información fiable con fuentes. Usa Browser Automation por dentro; tú solo le pides el tema.',
    icon: '🔭',
    gradient: 'from-cyan-500 to-blue-500',
    category: 'Research',
    difficulty: 'Media',
    setupMinutes: 3,
    connectors: [],
    mcps: [],
    tools: ['browser', 'http'],
    useCases: ['Investigación de temas', 'Comparativas', 'Resúmenes con fuentes'],
    rating: 4.8,
    installs: 6100,
    author: 'workestra',
    badges: ['AI Powered', 'Trending'],
    collections: ['trending'],
    install: {
      agents: [{ ref: 'a', name: 'Research Agent', emoji: '🔭', role: 'Investigación', model: M, tools: ['browser', 'http'], systemPrompt: 'Eres un investigador. Navega y busca para responder con hechos concretos y las fuentes (URLs). Sé riguroso.' }],
    },
  },
  {
    id: 'agent-data-analyst',
    kind: 'agent',
    name: 'Data Analyst',
    tagline: 'Interpreta datos y explica los hallazgos.',
    description: 'Un analista que recibe datos o una pregunta, razona sobre ellos y devuelve conclusiones claras con recomendaciones. Ideal para informes rápidos.',
    icon: '📈',
    gradient: 'from-teal-500 to-emerald-500',
    category: 'Operations',
    difficulty: 'Fácil',
    setupMinutes: 3,
    connectors: [],
    mcps: [],
    tools: ['http'],
    useCases: ['Informes ad-hoc', 'Interpretar métricas', 'Resúmenes ejecutivos'],
    rating: 4.7,
    installs: 4300,
    author: 'workestra',
    badges: ['Beginner Friendly'],
    collections: ['beginner'],
    install: {
      agents: [{ ref: 'a', name: 'Data Analyst', emoji: '📈', role: 'Análisis', model: M, tools: ['http'], systemPrompt: 'Eres un analista de datos. Explica qué dicen los datos, señala tendencias y da 2-3 recomendaciones accionables.' }],
    },
  },
  {
    id: 'agent-meeting-assistant',
    kind: 'agent',
    name: 'Meeting Assistant',
    tagline: 'Prepara agendas y resume reuniones.',
    description: 'Prepara la agenda de una reunión, toma notas y genera el acta con acuerdos y próximos pasos. Conecta tu calendario para contexto.',
    icon: '🗓️',
    gradient: 'from-fuchsia-500 to-pink-500',
    category: 'Executive',
    difficulty: 'Fácil',
    setupMinutes: 4,
    connectors: ['google-calendar'],
    mcps: [],
    tools: [],
    useCases: ['Actas de reunión', 'Agendas', 'Seguimiento de acuerdos'],
    rating: 4.6,
    installs: 3300,
    author: 'workestra',
    badges: ['New'],
    collections: ['new', 'beginner'],
    install: {
      agents: [{ ref: 'a', name: 'Meeting Assistant', emoji: '🗓️', role: 'Reuniones', model: M, tools: [], systemPrompt: 'Eres un asistente de reuniones. Prepara agendas y, tras la reunión, redacta un acta con decisiones, responsables y próximos pasos.' }],
    },
  },
  {
    id: 'agent-invoice-assistant',
    kind: 'agent',
    name: 'Invoice Assistant',
    tagline: 'Extrae los datos de una factura y los valida.',
    description: 'Un asistente que lee una factura (PDF o web), extrae proveedor, importe, impuestos y fecha, y comprueba que cuadre. Usa Browser Automation para portales de proveedores.',
    icon: '🧾',
    gradient: 'from-slate-500 to-slate-700',
    category: 'Finance',
    difficulty: 'Media',
    setupMinutes: 5,
    connectors: [],
    mcps: [],
    tools: ['browser'],
    useCases: ['Cuentas por pagar', 'Extracción de facturas', 'Validación de importes'],
    rating: 4.7,
    installs: 2900,
    author: 'workestra',
    badges: ['AI Powered'],
    collections: ['trending'],
    install: {
      agents: [{ ref: 'a', name: 'Invoice Assistant', emoji: '🧾', role: 'Facturas', model: M, tools: ['browser'], systemPrompt: 'Eres un asistente de cuentas por pagar. Extrae proveedor, número, fecha, base, impuestos y total de la factura, y verifica que el total cuadre. Devuelve un JSON claro.' }],
    },
  },

  // ---------------------------------- AUTOMATIONS ----------------------------------
  {
    id: 'ai-news-digest',
    kind: 'automation',
    name: 'AI News Digest',
    tagline: 'Cada día, la IA elige las 5 noticias de IA más relevantes y las publica en Slack.',
    description:
      'Un boletín diario automático. Trae las noticias más recientes de IA desde NewsAPI, la IA las lee todas y selecciona las 5 más relevantes (lanzamientos de modelos, investigación con impacto, movimientos de las grandes, regulación y financiación), descarta clickbait y coberturas duplicadas, y publica un resumen limpio en tu canal de Slack, sin previews de enlaces. Solo tienes que pegar tu clave gratuita de NewsAPI y elegir el canal.',
    icon: '🗞️',
    gradient: 'from-sky-500 to-indigo-500',
    category: 'Operations',
    difficulty: 'Fácil',
    setupMinutes: 4,
    connectors: ['slack'],
    mcps: [],
    tools: [],
    useCases: ['Boletín diario de IA para tu equipo', 'Vigilancia del sector y la competencia', 'Radar de lanzamientos y regulación'],
    requirements: ['Una clave gratuita de NewsAPI (newsapi.org)', 'Slack conectado'],
    rating: 4.9,
    installs: 0,
    author: 'workestra',
    badges: ['New', 'AI Powered'],
    collections: ['new', 'popular', 'beginner'],
    install: {
      workflow: {
        name: 'AI News Digest',
        doc: {
          nodes: [
            node('trigger', 'trigger', 40, 200, { event: 'cron', eventId: 'schedule' }),
            node('news', 'api', 300, 200, {
              method: 'GET',
              // Ventana de UN DÍA ordenada por popularidad, no «lo más reciente»: esta consulta tiene ~1.600
              // artículos al día, así que pedir las 30 más recientes devuelve los 24 minutos anteriores a la
              // ejecución —notas de prensa sueltas—. El plan gratuito de NewsAPI sirve con ~24 h de retraso,
              // de ahí que la ventana sea de -2d a -1d y no «las últimas 24 h» (que saldría vacía).
              url: 'https://newsapi.org/v2/everything?q=%22artificial%20intelligence%22%20OR%20%22generative%20AI%22%20OR%20OpenAI%20OR%20Anthropic&language=en&from={{fecha:-2d}}&to={{fecha:-1d}}&sortBy=popularity&pageSize=100',
              headers: '{"X-Api-Key":"YOUR_NEWSAPI_KEY"}',
            }),
            node('digest', 'llm', 560, 200, {
              model: M,
              prompt:
                'You are the editor of a daily AI news briefing. You receive a list of articles as JSON (from NewsAPI). Analyse them and PICK THE 5 MOST RELEVANT for someone who follows the AI industry closely: prioritise model launches, research with real impact, moves by the leading labs and companies, regulation, and meaningful funding. Drop clickbait, listicles, promotional content, thin opinion pieces and duplicates (if several outlets cover the same story, keep the best one). If a story already appears in the <ya-escrito> block (previous digests), skip it and pick the next best one — even if the headline, the outlet or the link is different; only bring a story back if there is genuinely new, material development.\n\nReturn ONLY the final Slack message, with no preamble or explanation, in exactly this format:\n\n*🤖 AI News Digest — <today\'s date>*\n\n*1. <clear, concise headline>*\n> <why it matters, 1-2 sentences>\n<article url>\n\n(and so on, up to 5)\n\n_Source: NewsAPI · curated by AI_\n\nRules: Slack mrkdwn — bold with a SINGLE asterisk (*like this*), NEVER double. Do not invent headlines or URLs: use exactly the ones from the JSON. Write in English, natural and to the point.',
              input: "Yesterday's articles (NewsAPI JSON):\n{{http:news.json.articles}}",
              // Sin esto, cada ejecución arranca en blanco y vuelve a elegir las mismas historias: el paso
              // recuerda los boletines de días anteriores y se le pide que no los repita.
              noRepetir: true,
            }),
            node('slack', 'connector', 820, 200, {
              provider: 'slack',
              connectorId: null,
              action: 'post-message',
              actionParams: { channel: '', text: '{{agent:digest.output}}' },
              method: 'POST',
              path: '/chat.postMessage',
              body: '{"channel":"","text":"{{agent:digest.output}}","unfurl_links":false,"unfurl_media":false}',
            }),
            node('end', 'end', 1080, 200, {}),
          ],
          edges: [edge('trigger', 'news'), edge('news', 'digest'), edge('digest', 'slack'), edge('slack', 'end')],
          comments: [
            {
              id: 'c-readme',
              text:
                '🗞️ AI News Digest — a daily AI briefing in Slack\n' +
                '- 1. NewsAPI (HTTP): fetches a full day of AI articles in English, ranked by popularity. Paste your free newsapi.org key in this node\'s Headers (replace YOUR_NEWSAPI_KEY).\n' +
                '- 2. AI (digest): reads them all and picks the 5 most relevant — model launches, real research, moves by the big labs, regulation, funding. Drops clickbait and duplicates.\n' +
                '     "Don\'t repeat what it already wrote" is ON: it remembers the last week of digests and skips stories it already covered, even from another outlet. Day 1 sends a normal digest — there is nothing to remember yet.\n' +
                '- 3. Slack: posts the digest. Open this node and pick your channel. Link previews are off so the 5 URLs stay compact.\n' +
                '- Schedule: open the Trigger node to choose what time it runs each day.\n' +
                '- Tune it: the prompt and model live in the "digest" node; the topic filter is the q= in the news node\'s URL.\n' +
                '- Why a day-old window: the free NewsAPI plan serves articles with a ~24h delay, so the news node asks for the -2d..-1d window. On a paid key you can move it to {{fecha:-1d}}..{{fecha}}.',
              position: { x: 40, y: -260 },
              color: 'amber',
              width: 640,
              height: 210,
            },
          ],
        },
      },
    },
  },
  {
    id: 'auto-gmail-slack',
    kind: 'automation',
    name: 'Gmail → Slack',
    tagline: 'Avisa en Slack cuando llega un correo importante.',
    description: 'Cuando entra un correo (o uno que cumple un criterio), resume el mensaje y lo publica en un canal de Slack. Menos bandeja, más contexto para el equipo.',
    icon: '🔔',
    gradient: 'from-purple-500 to-violet-500',
    category: 'Operations',
    difficulty: 'Fácil',
    setupMinutes: 5,
    connectors: ['gmail', 'slack'],
    mcps: [],
    tools: [],
    useCases: ['Avisos de bandeja', 'Correos de clientes', 'Alertas de equipo'],
    rating: 4.8,
    installs: 5400,
    author: 'community',
    badges: ['Popular', 'Beginner Friendly'],
    collections: ['popular', 'beginner'],
    install: {
      workflow: {
        name: 'Gmail → Slack',
        doc: {
          nodes: [
            node('trigger', 'trigger', 40, 160, { event: 'webhook' }),
            node('sum', 'llm', 300, 160, { model: M, prompt: 'Resume el correo en una frase clara.', input: 'De: {{ticket.summary}}\n{{ticket.description}}' }),
            node('slack', 'connector', 560, 160, { provider: 'slack', connectorId: null, method: 'POST', path: '/chat.postMessage', body: '{"channel":"#general","text":"📩 {{agent:sum.output}}"}' }),
            node('end', 'end', 820, 160, {}),
          ],
          edges: [edge('trigger', 'sum'), edge('sum', 'slack'), edge('slack', 'end')],
          comments: [],
        },
      },
    },
  },
  {
    id: 'auto-sentry-triage',
    kind: 'automation',
    name: 'Sentry → Jira Ticket',
    tagline: 'Cuando Sentry reporta un error, la IA lo triaja y crea el ticket en Jira.',
    description:
      'Arranca en tiempo real en cuanto aparece un nuevo issue en Sentry. La IA resume el error y su gravedad, y automáticamente crea una incidencia en tu board de Jira con el triaje y el enlace al issue. Perfecto para no perder ningún error y probar el disparador de Sentry de punta a punta.',
    icon: '🔺',
    gradient: 'from-violet-500 to-purple-700',
    category: 'Engineering',
    difficulty: 'Fácil',
    setupMinutes: 5,
    connectors: ['sentry', 'jira'],
    mcps: [],
    tools: [],
    useCases: ['Errores → tickets', 'Triaje de guardia', 'Probar el disparador de Sentry'],
    variables: [{ key: 'projectKey', label: 'Clave del proyecto de Jira', example: 'KAN' }],
    requirements: ['Sentry conectado + la app de Workestra instalada en tu org', 'Jira conectado'],
    rating: 4.9,
    installs: 640,
    author: 'workestra',
    badges: ['New', 'AI Powered'],
    collections: ['new'],
    install: {
      workflow: {
        name: 'Sentry → Jira Ticket',
        doc: {
          nodes: [
            node('trigger', 'trigger', 40, 160, { event: 'webhook', eventId: 'sentry.issue_created' }),
            node('triage', 'llm', 320, 160, {
              model: M,
              prompt: 'Eres un ingeniero de guardia. En 2-3 frases: resume el error, di su gravedad (alta/media/baja) y un primer paso concreto para investigarlo.',
              input: 'Issue: {{issue.title}}\nNivel: {{issue.level}}\nCausa probable: {{issue.culprit}}\nEnlace: {{issue.permalink}}',
            }),
            node('jira', 'connector', 600, 160, {
              provider: 'jira',
              connectorId: null,
              method: 'POST',
              // El runtime resuelve {cloudid} del sitio de Jira. Cambia «KAN» por la clave de tu proyecto.
              path: '/ex/jira/{cloudid}/rest/api/3/issue',
              body: JSON.stringify({
                fields: {
                  project: { key: 'KAN' },
                  summary: 'Sentry {{issue.shortId}}: {{issue.title}}',
                  issuetype: { name: 'Task' },
                  description: {
                    type: 'doc',
                    version: 1,
                    content: [
                      { type: 'paragraph', content: [{ type: 'text', text: 'Nuevo issue de Sentry (nivel {{issue.level}}).' }] },
                      { type: 'paragraph', content: [{ type: 'text', text: 'Triaje: {{agent:triage.output}}' }] },
                      { type: 'paragraph', content: [{ type: 'text', text: 'Enlace: {{issue.permalink}}' }] },
                    ],
                  },
                },
              }),
            }),
            node('note', 'tool', 880, 160, { message: '🔺 Sentry {{issue.shortId}} → Jira {{connector:jira.json.key}}' }),
            node('end', 'end', 1160, 160, {}),
          ],
          edges: [edge('trigger', 'triage'), edge('triage', 'jira'), edge('jira', 'note'), edge('note', 'end')],
          comments: [],
        },
      },
    },
  },
  {
    id: 'auto-daily-report',
    kind: 'automation',
    name: 'Daily Report',
    tagline: 'Un resumen diario automático a tu canal.',
    description: 'Cada día, recopila el estado (ventas, incidencias, lo que definas), lo resume con IA y lo publica en Slack. Se dispara por horario.',
    icon: '📊',
    gradient: 'from-orange-500 to-amber-500',
    category: 'Operations',
    difficulty: 'Fácil',
    setupMinutes: 6,
    connectors: ['slack'],
    mcps: [],
    tools: ['http'],
    useCases: ['Resumen diario', 'Standup asíncrono', 'KPIs del día'],
    rating: 4.6,
    installs: 3100,
    author: 'community',
    badges: ['Beginner Friendly'],
    collections: ['beginner'],
    install: {
      workflow: {
        name: 'Daily Report',
        doc: {
          nodes: [
            node('trigger', 'trigger', 40, 160, { event: 'cron' }),
            node('sum', 'llm', 300, 160, { model: M, prompt: 'Redacta un resumen diario breve y motivador con los datos aportados.', input: 'Datos de hoy:\n{{ticket.description}}' }),
            node('slack', 'connector', 560, 160, { provider: 'slack', connectorId: null, method: 'POST', path: '/chat.postMessage', body: '{"channel":"#daily","text":"☀️ Resumen de hoy:\\n{{agent:sum.output}}"}' }),
            node('end', 'end', 820, 160, {}),
          ],
          edges: [edge('trigger', 'sum'), edge('sum', 'slack'), edge('slack', 'end')],
          comments: [],
        },
      },
    },
  },
  {
    id: 'auto-lead-qualification',
    kind: 'automation',
    name: 'Lead Qualification',
    tagline: 'Puntúa cada lead entrante y enruta el flujo.',
    description: 'Cuando llega un lead, la IA lo puntúa; si es caliente, avisa a ventas; si no, lo guarda para nurturing. Bifurca según la puntuación.',
    icon: '🎯',
    gradient: 'from-lime-500 to-green-500',
    category: 'Sales',
    difficulty: 'Media',
    setupMinutes: 7,
    connectors: ['slack'],
    mcps: [],
    tools: [],
    useCases: ['Inbound', 'Routing de leads', 'Priorización'],
    rating: 4.7,
    installs: 2400,
    author: 'community',
    badges: ['Sales Automation', 'Trending'],
    collections: ['trending'],
    install: {
      workflow: {
        name: 'Lead Qualification',
        doc: {
          nodes: [
            node('trigger', 'trigger', 40, 200, { event: 'webhook' }),
            node('score', 'llm', 300, 200, { model: M, prompt: 'Puntúa el lead como CALIENTE o FRÍO con una frase.', input: '{{ticket.summary}}\n{{ticket.description}}' }),
            node('hot', 'condition', 560, 200, { expression: 'agent:score.output ~ CALIENTE' }),
            node('nurture', 'tool', 820, 100, { message: 'Lead frío guardado para nurturing.' }),
            node('end1', 'end', 1080, 100, {}),
            node('notify', 'connector', 820, 300, { provider: 'slack', connectorId: null, method: 'POST', path: '/chat.postMessage', body: '{"channel":"#ventas","text":"🔥 Lead caliente: {{ticket.summary}}"}' }),
            node('end2', 'end', 1080, 300, {}),
          ],
          edges: [edge('trigger', 'score'), edge('score', 'hot'), edge('hot', 'nurture', 'false'), edge('nurture', 'end1'), edge('hot', 'notify', 'true'), edge('notify', 'end2')],
          comments: [],
        },
      },
    },
  },
  {
    id: 'auto-ai-email-reply',
    kind: 'automation',
    name: 'AI Email Reply',
    tagline: 'Responde correos automáticamente con IA.',
    description: 'Para correos entrantes, genera un borrador de respuesta con tu tono y lo envía (o lo deja para revisión). Reduce el tiempo de respuesta a segundos.',
    icon: '↩️',
    gradient: 'from-blue-500 to-indigo-500',
    category: 'Customer Support',
    difficulty: 'Media',
    setupMinutes: 6,
    connectors: ['gmail'],
    mcps: [],
    tools: [],
    useCases: ['Respuestas automáticas', 'Soporte de primer nivel', 'FAQ por correo'],
    rating: 4.6,
    installs: 2700,
    author: 'community',
    badges: ['AI Powered'],
    collections: ['popular'],
    install: {
      workflow: {
        name: 'AI Email Reply',
        doc: {
          nodes: [
            node('trigger', 'trigger', 40, 160, { event: 'webhook' }),
            node('reply', 'llm', 300, 160, { model: M, prompt: 'Eres soporte. Redacta una respuesta útil y amable al correo.', input: '{{ticket.summary}}\n{{ticket.description}}' }),
            node('note', 'tool', 560, 160, { message: 'Respuesta lista: {{agent:reply.output}}' }),
            node('end', 'end', 820, 160, {}),
          ],
          edges: [edge('trigger', 'reply'), edge('reply', 'note'), edge('note', 'end')],
          comments: [],
        },
      },
    },
  },

  // ------------------------------ BROWSER AUTOMATION ------------------------------
  {
    id: 'browser-extract-tables',
    kind: 'browser',
    name: 'Extract Tables',
    tagline: 'Extrae tablas de cualquier web a datos limpios.',
    description: 'Abre una página, localiza las tablas y las devuelve como datos estructurados listos para usar. Sin saber nada de scraping.',
    icon: '📋',
    gradient: 'from-emerald-500 to-teal-500',
    category: 'Operations',
    difficulty: 'Media',
    setupMinutes: 3,
    connectors: [],
    mcps: [],
    tools: ['browser'],
    useCases: ['Extraer tablas', 'Recopilar datos', 'Migrar información'],
    variables: [{ key: 'url', label: 'URL de la página', example: 'https://ejemplo.com/precios' }],
    rating: 4.7,
    installs: 1900,
    author: 'workestra',
    badges: ['Browser Automation'],
    collections: ['browser', 'trending'],
    install: {
      agents: [{ ref: 'a', name: 'Table Extractor', emoji: '📋', role: 'Extracción web', model: M, tools: ['browser'], systemPrompt: 'Abres la web indicada con el navegador, localizas las tablas y devuelves su contenido como datos estructurados (JSON). Extrae texto, no capturas.' }],
      workflow: {
        name: 'Extract Tables',
        doc: {
          nodes: [
            node('trigger', 'trigger', 40, 160, { event: 'manual' }),
            node('extract', 'agent', 300, 160, { agentRef: 'a', input: 'Extrae las tablas de: {{ticket.summary}}' }),
            node('end', 'end', 560, 160, {}),
          ],
          edges: [edge('trigger', 'extract'), edge('extract', 'end')],
          comments: [],
        },
      },
    },
  },
  {
    id: 'browser-price-monitor',
    kind: 'browser',
    name: 'Price Monitor',
    tagline: 'Vigila precios y avisa si cambian.',
    description: 'Revisa periódicamente el precio de un producto en una web y te avisa por Slack si sube o baja. Ideal para competencia o compras.',
    icon: '🏷️',
    gradient: 'from-amber-500 to-yellow-500',
    category: 'Ecommerce',
    difficulty: 'Media',
    setupMinutes: 6,
    connectors: ['slack'],
    mcps: [],
    tools: ['browser'],
    useCases: ['Vigilancia de precios', 'Competencia', 'Alertas de stock'],
    variables: [{ key: 'url', label: 'URL del producto', example: 'https://tienda.com/producto' }],
    rating: 4.6,
    installs: 1500,
    author: 'community',
    badges: ['Browser Automation', 'New'],
    collections: ['browser', 'new'],
    install: {
      agents: [{ ref: 'a', name: 'Price Watcher', emoji: '🏷️', role: 'Vigilancia web', model: M, tools: ['browser'], systemPrompt: 'Abres la URL del producto, extraes el precio actual y lo comparas con el objetivo. Indica si hay cambio relevante y el precio exacto.' }],
      workflow: {
        name: 'Price Monitor',
        doc: {
          nodes: [
            node('trigger', 'trigger', 40, 160, { event: 'cron' }),
            node('check', 'agent', 300, 160, { agentRef: 'a', input: 'Comprueba el precio en: {{ticket.summary}}' }),
            node('slack', 'connector', 560, 160, { provider: 'slack', connectorId: null, method: 'POST', path: '/chat.postMessage', body: '{"channel":"#precios","text":"🏷️ {{agent:check.output}}"}' }),
            node('end', 'end', 820, 160, {}),
          ],
          edges: [edge('trigger', 'check'), edge('check', 'slack'), edge('slack', 'end')],
          comments: [],
        },
      },
    },
  },
  {
    id: 'browser-website-testing',
    kind: 'browser',
    name: 'Website Testing',
    tagline: 'Prueba tu web como un usuario real y reporta fallos.',
    description: 'Un agente QA que recorre un flujo de tu web (login, formulario, checkout), valida que funcione y avisa con captura si algo falla. La misma base que el equipo QA.',
    icon: '🧪',
    gradient: 'from-rose-500 to-pink-500',
    category: 'Development',
    difficulty: 'Avanzada',
    setupMinutes: 5,
    connectors: [],
    mcps: [],
    tools: ['browser'],
    useCases: ['QA de UI', 'Smoke tests', 'Regresiones'],
    rating: 4.8,
    installs: 2200,
    author: 'workestra',
    badges: ['Browser Automation', 'AI Powered'],
    collections: ['browser', 'trending'],
    install: {
      agents: [{ ref: 'qa', name: 'QA de navegador', emoji: '🧪', role: 'Testing', model: M, tools: ['browser'], systemPrompt: 'Eres un ingeniero de QA. Usa Browser Automation para ejecutar la prueba de UI paso a paso; si algo falla, captura pantalla y describe el paso, lo esperado y lo obtenido. Empieza por «PASA» o «FALLA».' }],
      workflow: {
        name: 'Website Testing',
        doc: {
          nodes: [
            node('trigger', 'trigger', 40, 160, { event: 'manual' }),
            node('test', 'agent', 300, 160, { agentRef: 'qa', input: 'Abre la web y ejecuta la prueba de UI. Empieza por PASA o FALLA.' }),
            node('end', 'end', 560, 160, {}),
          ],
          edges: [edge('trigger', 'test'), edge('test', 'end')],
          comments: [],
        },
      },
    },
  },

  // ------------------------------- MCP SOLUTIONS -------------------------------
  {
    id: 'mcp-github-expert',
    kind: 'mcp',
    name: 'GitHub Expert',
    tagline: 'Un experto conectado a GitHub por MCP.',
    description: 'Un agente que trabaja con tus repos: issues, PRs, revisiones y búsquedas de código, a través del servidor MCP oficial de GitHub. Tú le hablas en lenguaje natural.',
    icon: '🐙',
    gradient: 'from-zinc-600 to-zinc-800',
    category: 'Development',
    difficulty: 'Media',
    setupMinutes: 5,
    connectors: [],
    mcps: ['GitHub'],
    tools: [],
    useCases: ['Gestión de issues', 'Revisión de PRs', 'Búsqueda de código'],
    requirements: ['Acceso al MCP de GitHub'],
    rating: 4.8,
    installs: 3600,
    author: 'workestra',
    badges: ['MCP Ready', 'Popular'],
    collections: ['mcp', 'popular'],
    install: {
      agents: [{ ref: 'a', name: 'GitHub Expert', emoji: '🐙', role: 'MCP GitHub', model: M, tools: [], mcpServers: [{ name: 'GitHub', url: 'https://api.githubcopilot.com/mcp/' }], systemPrompt: 'Eres un experto en GitHub. Usa las herramientas MCP de GitHub para gestionar issues, PRs y buscar código. Explica lo que haces en lenguaje claro.' }],
    },
  },
  {
    id: 'mcp-jira-expert',
    kind: 'mcp',
    name: 'Jira Expert',
    tagline: 'Gestiona Jira hablando en lenguaje natural.',
    description: 'Un agente que crea y actualiza tickets, consulta sprints y organiza el backlog vía el MCP de Atlassian. Ideal para PMs y equipos ágiles.',
    icon: '🟦',
    gradient: 'from-blue-500 to-sky-600',
    category: 'Development',
    difficulty: 'Media',
    setupMinutes: 5,
    connectors: [],
    mcps: ['Atlassian'],
    tools: [],
    useCases: ['Gestión de tickets', 'Sprints', 'Backlog'],
    rating: 4.7,
    installs: 2100,
    author: 'workestra',
    badges: ['MCP Ready'],
    collections: ['mcp'],
    install: {
      agents: [{ ref: 'a', name: 'Jira Expert', emoji: '🟦', role: 'MCP Jira', model: M, tools: [], mcpServers: [{ name: 'Atlassian', url: 'https://mcp.atlassian.com/v1/sse' }], systemPrompt: 'Eres un experto en Jira/Atlassian. Usa las herramientas MCP para crear/actualizar tickets, consultar sprints y organizar el backlog.' }],
    },
  },
  {
    id: 'mcp-notion-expert',
    kind: 'mcp',
    name: 'Notion Expert',
    tagline: 'Tu wiki de Notion, operada por un agente.',
    description: 'Un agente que lee y escribe en tus páginas y bases de datos de Notion vía MCP. Documenta, busca y organiza sin salir del chat.',
    icon: '📔',
    gradient: 'from-neutral-500 to-neutral-700',
    category: 'Operations',
    difficulty: 'Media',
    setupMinutes: 5,
    connectors: [],
    mcps: ['Notion'],
    tools: [],
    useCases: ['Documentación', 'Bases de conocimiento', 'Búsqueda interna'],
    rating: 4.6,
    installs: 1700,
    author: 'workestra',
    badges: ['MCP Ready', 'New'],
    collections: ['mcp', 'new'],
    install: {
      agents: [{ ref: 'a', name: 'Notion Expert', emoji: '📔', role: 'MCP Notion', model: M, tools: [], mcpServers: [{ name: 'Notion', url: 'https://mcp.notion.com/mcp' }], systemPrompt: 'Eres un experto en Notion. Usa las herramientas MCP para leer/escribir páginas y bases de datos, documentar y buscar información.' }],
    },
  },
  {
    id: 'mcp-salesforce-expert',
    kind: 'mcp',
    name: 'Salesforce Expert',
    tagline: 'Consulta y actualiza tu CRM por MCP.',
    description: 'Un agente que trabaja con oportunidades, cuentas y contactos de Salesforce vía MCP. Pregúntale por el pipeline o pídele que actualice un registro.',
    icon: '☁️',
    gradient: 'from-sky-500 to-blue-600',
    category: 'Sales',
    difficulty: 'Media',
    setupMinutes: 6,
    connectors: [],
    mcps: ['Salesforce'],
    tools: [],
    useCases: ['Consultar pipeline', 'Actualizar registros', 'Reporting de CRM'],
    rating: 4.6,
    installs: 1400,
    author: 'workestra',
    badges: ['MCP Ready', 'Enterprise'],
    collections: ['mcp'],
    install: {
      agents: [{ ref: 'a', name: 'Salesforce Expert', emoji: '☁️', role: 'MCP Salesforce', model: M, tools: [], mcpServers: [{ name: 'Salesforce', url: 'https://mcp.salesforce.com/mcp' }], systemPrompt: 'Eres un experto en Salesforce. Usa las herramientas MCP para consultar y actualizar oportunidades, cuentas y contactos, y explicar el estado del pipeline.' }],
    },
  },

  // ------------------------------ MÁS AI TEAMS ------------------------------
  {
    id: 'team-marketing',
    kind: 'team',
    name: 'Marketing Team',
    tagline: 'Idea, redacta y programa contenido de marketing.',
    description: 'Un equipo de marketing que genera ideas de campaña, redacta el contenido (posts, emails, anuncios) con tu tono y prepara un calendario de publicación. Del brief a las piezas, en minutos.',
    icon: '📣',
    gradient: 'from-pink-500 to-rose-500',
    category: 'Marketing',
    difficulty: 'Media',
    setupMinutes: 8,
    connectors: ['slack'],
    mcps: [],
    tools: ['http'],
    useCases: ['Calendario de contenidos', 'Campañas', 'Copys de anuncios'],
    rating: 4.7,
    installs: 2180,
    author: 'workestra',
    badges: ['AI Powered', 'Trending'],
    collections: ['trending', 'ai-teams'],
    install: {
      agents: [
        { ref: 'lead', name: 'Marketing Lead', emoji: '🧭', role: 'Routes the brief to the right marketing specialists', model: M, tools: [], isOrchestrator: true, systemPrompt: 'Eres el Marketing Lead de un equipo de contenido. Lee el brief de campaña y decide qué especialista(s) deben intervenir: estrategia (ángulos y mensaje), copy (redacción de piezas), creatividad (dirección visual y formatos) o planificación (calendario y distribución). Elige solo los necesarios y reparte el trabajo con instrucciones claras y el objetivo de cada pieza.' },
        { ref: 'strategist', name: 'Content Strategist', emoji: '🧠', role: 'Defines campaign angles and channel messaging', model: M, tools: [], systemPrompt: 'Eres estratega de contenido. A partir del brief, propón 2-3 ángulos de campaña, el mensaje clave y el público objetivo para cada canal. Prioriza los canales con mayor impacto y justifica brevemente cada elección.' },
        { ref: 'copywriter', name: 'Copywriter', emoji: '✍️', role: 'Writes posts, emails and ad copy', model: M, tools: [], systemPrompt: 'Eres copywriter. Escribe piezas breves y persuasivas (post, email, anuncio) con la voz de la marca y una CTA clara. Adapta el tono y la longitud a cada canal y ofrece al menos una variante para probar.' },
        { ref: 'designer', name: 'Creative Designer', emoji: '🎨', role: 'Proposes visual direction and asset formats', model: M, tools: [], systemPrompt: 'Eres director creativo. A partir del brief, propón la dirección visual: concepto, paleta, tipografía y los formatos de asset por canal (imagen, carrusel, vídeo corto). Da indicaciones concretas y accionables para que el equipo de diseño las ejecute.' },
        { ref: 'scheduler', name: 'Content Planner', emoji: '🗓️', role: 'Plans the publishing calendar and distribution', model: M, tools: [], systemPrompt: 'Eres planificador de contenidos. Organiza un calendario de publicación con fechas, canales y frecuencia, y define el plan de distribución para maximizar el alcance. Señala dependencias entre piezas y los mejores momentos para publicar.' },
      ],
      workflow: {
        name: 'Marketing Team',
        doc: {
          nodes: [
            node('trigger', 'trigger', 40, 285, { event: 'manual' }),
            node('lead', 'router', 340, 285, { agentRef: 'lead', input: 'Reparte este brief de marketing entre los especialistas más adecuados (estrategia, copy, creatividad, planificación):\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('strategist', 'agent', 640, 60, { agentRef: 'strategist', input: 'Define ángulos, mensaje clave y público objetivo para la campaña:\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('copywriter', 'agent', 640, 210, { agentRef: 'copywriter', input: 'Redacta las piezas de contenido (post, email y anuncio) para:\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('designer', 'agent', 640, 360, { agentRef: 'designer', input: 'Propón la dirección visual y los formatos de asset por canal para:\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('scheduler', 'agent', 640, 510, { agentRef: 'scheduler', input: 'Prepara el calendario de publicación y el plan de distribución para:\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('end', 'end', 940, 285, {}),
          ],
          edges: [
            edge('trigger', 'lead'),
            edge('lead', 'strategist'),
            edge('lead', 'copywriter'),
            edge('lead', 'designer'),
            edge('lead', 'scheduler'),
            edge('strategist', 'end'),
            edge('copywriter', 'end'),
            edge('designer', 'end'),
            edge('scheduler', 'end'),
          ],
          comments: [],
        },
      },
    },
  },
  {
    id: 'team-finance',
    kind: 'team',
    name: 'Finance Team',
    tagline: 'Procesa facturas, concilia y avisa de anomalías.',
    description: 'Equipo financiero que lee facturas, valida importes e impuestos, marca anomalías y prepara un resumen para contabilidad. Reduce el trabajo manual de cuentas por pagar.',
    icon: '💰',
    gradient: 'from-emerald-500 to-green-600',
    category: 'Finance',
    difficulty: 'Avanzada',
    setupMinutes: 12,
    connectors: ['slack'],
    mcps: [],
    tools: ['browser', 'http'],
    useCases: ['Cuentas por pagar', 'Conciliación', 'Detección de anomalías'],
    rating: 4.6,
    installs: 1290,
    author: 'workestra',
    badges: ['Enterprise', 'AI Powered'],
    collections: ['ai-teams'],
    install: {
      agents: [
        { ref: 'lead', name: 'Finance Team Lead', emoji: '🧑‍✈️', role: 'Routes financial work to the right specialist', model: M, tools: [], isOrchestrator: true, systemPrompt: 'Eres el Team Lead del equipo financiero de cuentas por pagar. Lee la solicitud (una factura, una discrepancia o una petición de conciliación) y decide qué especialista(s) deben actuar: extracción de datos de factura, validación fiscal, auditoría de anomalías o conciliación contable. Elige solo los necesarios y reparte el trabajo con instrucciones claras y el contexto relevante.' },
        { ref: 'processor', name: 'Invoice Processor', emoji: '🧾', role: 'Extracts and structures invoice data', model: M, tools: [], systemPrompt: 'Eres especialista en procesamiento de facturas. A partir del documento (PDF o web), extrae proveedor, número, fecha, base imponible, impuestos y total, y verifica que las cifras cuadren. Devuelve un JSON claro y señala cualquier campo ausente o ilegible.' },
        { ref: 'tax', name: 'Tax & Compliance Specialist', emoji: '🧮', role: 'Validates taxes and compliance', model: M, tools: [], systemPrompt: 'Eres especialista fiscal y de cumplimiento. Revisa que los tipos impositivos (IVA/retenciones) sean correctos según el proveedor y el país, comprueba que los datos fiscales estén completos y marca cualquier riesgo de cumplimiento. Explica cada corrección con concisión.' },
        { ref: 'auditor', name: 'Anomaly Auditor', emoji: '🔍', role: 'Detects anomalies and fraud', model: M, tools: [], systemPrompt: 'Eres auditor de anomalías en cuentas por pagar. Revisa los datos de la factura y detecta duplicados, importes fuera de rango, proveedores sospechosos, impuestos incorrectos o señales de fraude. Clasifica cada hallazgo por gravedad y recomienda si aprobar, revisar o bloquear el pago.' },
        { ref: 'reconciler', name: 'Reconciliation & Accounting', emoji: '📊', role: 'Reconciles and summarizes for accounting', model: M, tools: [], systemPrompt: 'Eres especialista en conciliación contable. Cruza la factura con la orden de compra y el registro contable, resuelve discrepancias y prepara un resumen claro para contabilidad con el asiento propuesto y los próximos pasos. Sé preciso y accionable.' },
      ],
      workflow: {
        name: 'Finance Team',
        doc: {
          nodes: [
            node('trigger', 'trigger', 40, 285, { event: 'manual' }),
            node('lead', 'router', 340, 285, { agentRef: 'lead', input: 'Analiza esta solicitud financiera y enrútala al especialista o especialistas adecuados (extracción de factura, validación fiscal, auditoría de anomalías o conciliación):\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('processor', 'agent', 640, 60, { agentRef: 'processor', input: 'Procesa y extrae los datos estructurados de esta factura, verificando que los importes cuadren:\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('tax', 'agent', 640, 210, { agentRef: 'tax', input: 'Valida los impuestos y el cumplimiento fiscal de esta factura, indicando correcciones si las hay:\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('auditor', 'agent', 640, 360, { agentRef: 'auditor', input: 'Audita esta factura en busca de duplicados, importes atípicos y señales de fraude, clasificando por gravedad:\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('reconciler', 'agent', 640, 510, { agentRef: 'reconciler', input: 'Concilia esta factura con la orden de compra correspondiente y prepara el resumen para contabilidad:\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('end', 'end', 940, 285, {}),
          ],
          edges: [
            edge('trigger', 'lead'),
            edge('lead', 'processor'),
            edge('lead', 'tax'),
            edge('lead', 'auditor'),
            edge('lead', 'reconciler'),
            edge('processor', 'end'),
            edge('tax', 'end'),
            edge('auditor', 'end'),
            edge('reconciler', 'end'),
          ],
          comments: [],
        },
      },
    },
  },
  {
    id: 'team-legal',
    kind: 'team',
    name: 'Legal Team',
    tagline: 'Revisa contratos y señala cláusulas de riesgo.',
    description: 'Equipo legal que lee un contrato, resume sus términos, señala cláusulas de riesgo y sugiere redacciones alternativas. Un primer filtro antes de que lo vea un abogado.',
    icon: '⚖️',
    gradient: 'from-slate-500 to-gray-700',
    category: 'Legal',
    difficulty: 'Avanzada',
    setupMinutes: 7,
    connectors: [],
    mcps: [],
    tools: [],
    useCases: ['Revisión de contratos', 'Análisis de riesgo', 'Resumen de términos'],
    rating: 4.7,
    installs: 980,
    author: 'workestra',
    badges: ['Enterprise'],
    collections: ['ai-teams', 'new'],
    install: {
      agents: [
        { ref: 'lead', name: 'Legal Team Lead', emoji: '⚖️', role: 'Routes the contract to the right specialist(s)', model: M, tools: [], isOrchestrator: true, systemPrompt: 'Eres el Team Lead de un equipo legal. Lee el contrato o la consulta de entrada e identifica qué necesita: resumen y análisis de términos, detección de cláusulas de riesgo, propuesta de redacciones alternativas o verificación de cumplimiento normativo. Decide qué especialista(s) deben intervenir y reparte el trabajo con instrucciones claras; elige solo los necesarios y pueden entrar varios a la vez.' },
        { ref: 'analyst', name: 'Contract Analyst', emoji: '📜', role: 'Summarizes terms and key obligations', model: M, tools: [], systemPrompt: 'Eres analista de contratos. Resume el contrato de forma estructurada: partes, objeto, plazos, obligaciones económicas y condiciones de terminación. Destaca los puntos clave que requieren atención y expón todo en lenguaje claro para un lector no jurista.' },
        { ref: 'risk', name: 'Risk Assessor', emoji: '🚩', role: 'Flags risky clauses and their severity', model: M, tools: [], systemPrompt: 'Eres evaluador de riesgo legal. Identifica cláusulas de riesgo (responsabilidad, indemnización, rescisión, propiedad intelectual, exclusividad) y clasifica su gravedad como alta, media o baja. Explica por qué cada cláusula es problemática y qué exposición genera.' },
        { ref: 'drafter', name: 'Clause Drafter', emoji: '✍️', role: 'Proposes safer alternative wording', model: M, tools: [], systemPrompt: 'Eres redactor legal. Para las cláusulas de riesgo señaladas, propón redacciones alternativas más equilibradas y en lenguaje claro. Explica brevemente qué mejora cada propuesta y recuerda que no sustituyes el criterio final de un abogado.' },
        { ref: 'compliance', name: 'Compliance Checker', emoji: '✅', role: 'Checks regulatory and policy compliance', model: M, tools: [], systemPrompt: 'Eres especialista en cumplimiento normativo. Revisa el contrato frente a normativa aplicable (protección de datos, cláusulas abusivas, requisitos sectoriales) y señala vacíos u obligaciones legales que falten. Indica qué debería añadirse o corregirse para cumplir la normativa.' },
      ],
      workflow: {
        name: 'Legal Team',
        doc: {
          nodes: [
            node('trigger', 'trigger', 40, 285, { event: 'manual' }),
            node('lead', 'router', 340, 285, { agentRef: 'lead', input: 'Analiza esta entrada legal y asígnala al especialista o especialistas más adecuados (analista de contratos, evaluador de riesgo, redactor o cumplimiento):\n{{ticket.description}}' }),
            node('analyst', 'agent', 640, 60, { agentRef: 'analyst', input: 'Resume y estructura los términos de este contrato:\n{{ticket.description}}' }),
            node('risk', 'agent', 640, 210, { agentRef: 'risk', input: 'Detecta y clasifica las cláusulas de riesgo de este contrato:\n{{ticket.description}}' }),
            node('drafter', 'agent', 640, 360, { agentRef: 'drafter', input: 'Propón redacciones alternativas para las cláusulas de riesgo de:\n{{ticket.description}}' }),
            node('compliance', 'agent', 640, 510, { agentRef: 'compliance', input: 'Revisa el cumplimiento normativo de este contrato y señala vacíos legales:\n{{ticket.description}}' }),
            node('end', 'end', 940, 285, {}),
          ],
          edges: [
            edge('trigger', 'lead'),
            edge('lead', 'analyst'),
            edge('lead', 'risk'),
            edge('lead', 'drafter'),
            edge('lead', 'compliance'),
            edge('analyst', 'end'),
            edge('risk', 'end'),
            edge('drafter', 'end'),
            edge('compliance', 'end'),
          ],
          comments: [],
        },
      },
    },
  },
  {
    id: 'team-executive-assistant',
    kind: 'team',
    name: 'Executive Assistant Team',
    tagline: 'Tu chief of staff: agenda, correo y seguimiento.',
    description: 'Un equipo de asistencia ejecutiva que prioriza tu correo, prepara reuniones y hace seguimiento de tareas y compromisos. Como tener un chief of staff.',
    icon: '🎩',
    gradient: 'from-indigo-500 to-blue-500',
    category: 'Executive',
    difficulty: 'Media',
    setupMinutes: 9,
    connectors: ['gmail', 'google-calendar'],
    mcps: [],
    tools: [],
    useCases: ['Gestión del día', 'Priorizar correo', 'Seguimiento de compromisos'],
    rating: 4.8,
    installs: 2760,
    author: 'workestra',
    badges: ['Popular', 'AI Powered'],
    collections: ['popular', 'ai-teams'],
    install: {
      agents: [
        { ref: 'lead', name: 'Chief of Staff', emoji: '🎩', role: 'Coordinates the day and routes work', model: M, tools: [], isOrchestrator: true, systemPrompt: 'Eres el chief of staff del ejecutivo. Lee la entrada del usuario (correos, agenda, tareas pendientes) y decide a qué especialista(s) le toca: bandeja (triaje de correo), agenda (preparación de reuniones), seguimiento (compromisos y tareas) o redacción (borradores y comunicaciones). Elige solo los necesarios, reparte con instrucciones claras y prioriza lo urgente.' },
        { ref: 'inbox', name: 'Inbox Manager', emoji: '📥', role: 'Triages and prioritizes email', model: M, tools: [], systemPrompt: 'Eres el gestor de bandeja del ejecutivo. Clasifica y prioriza los correos: marca qué responder ya, qué delegar, qué archivar y qué puede esperar. Señala los remitentes clave y resume el hilo cuando aporte contexto.' },
        { ref: 'calendar', name: 'Calendar Planner', emoji: '🗓️', role: 'Prepares meetings and the agenda', model: M, tools: [], systemPrompt: 'Eres el planificador de agenda del ejecutivo. Revisa las reuniones del día, prepara agendas breves con objetivos y participantes, detecta conflictos de horario y propone huecos para trabajo enfocado. Sé concreto sobre qué preparar antes de cada reunión.' },
        { ref: 'tracker', name: 'Follow-up Tracker', emoji: '✅', role: 'Tracks commitments and open tasks', model: M, tools: [], systemPrompt: 'Eres el responsable de seguimiento del ejecutivo. Identifica compromisos, promesas y tareas pendientes; asigna responsable y fecha límite a cada uno y marca lo que está en riesgo o atrasado. Propón los recordatorios y próximos pasos concretos.' },
        { ref: 'writer', name: 'Comms Writer', emoji: '✍️', role: 'Drafts emails and communications', model: M, tools: [], systemPrompt: 'Eres el redactor de comunicaciones del ejecutivo. Redacta borradores claros, educados y accionables (respuestas de correo, mensajes de seguimiento, resúmenes) manteniendo el tono profesional del ejecutivo. Deja cada borrador listo para revisar y enviar.' },
      ],
      workflow: {
        name: 'Executive Assistant Team',
        doc: {
          nodes: [
            node('trigger', 'trigger', 40, 285, { event: 'manual' }),
            node('lead', 'router', 340, 285, { agentRef: 'lead', input: 'Coordina mi día y reparte al especialista o especialistas más adecuados según esto:\n{{ticket.description}}' }),
            node('inbox', 'agent', 640, 60, { agentRef: 'inbox', input: 'Prioriza y clasifica la bandeja según esto:\n{{ticket.description}}' }),
            node('calendar', 'agent', 640, 210, { agentRef: 'calendar', input: 'Prepara la agenda y las reuniones a partir de esto:\n{{ticket.description}}' }),
            node('tracker', 'agent', 640, 360, { agentRef: 'tracker', input: 'Extrae compromisos y tareas pendientes, y haz seguimiento de:\n{{ticket.description}}' }),
            node('writer', 'agent', 640, 510, { agentRef: 'writer', input: 'Redacta los borradores de correo o comunicación necesarios para:\n{{ticket.description}}' }),
            node('end', 'end', 940, 285, {}),
          ],
          edges: [
            edge('trigger', 'lead'),
            edge('lead', 'inbox'),
            edge('lead', 'calendar'),
            edge('lead', 'tracker'),
            edge('lead', 'writer'),
            edge('inbox', 'end'),
            edge('calendar', 'end'),
            edge('tracker', 'end'),
            edge('writer', 'end'),
          ],
          comments: [],
        },
      },
    },
  },
  {
    id: 'team-hr',
    kind: 'team',
    name: 'HR Team',
    tagline: 'Onboarding, dudas de personal y comunicación interna.',
    description: 'Equipo de RRHH que responde dudas de empleados (políticas, vacaciones, beneficios), prepara el onboarding de nuevas incorporaciones y redacta comunicaciones internas.',
    icon: '🧑‍🤝‍🧑',
    gradient: 'from-teal-500 to-cyan-600',
    category: 'HR',
    difficulty: 'Media',
    setupMinutes: 8,
    connectors: ['slack'],
    mcps: [],
    tools: [],
    useCases: ['Dudas de empleados', 'Onboarding', 'Comunicación interna'],
    rating: 4.6,
    installs: 1610,
    author: 'workestra',
    badges: ['Internal Productivity'],
    collections: ['ai-teams', 'new'],
    install: {
      agents: [
        { ref: 'lead', name: 'HR Team Lead', emoji: '🧑‍✈️', role: 'Routes HR requests to the right specialist', model: M, tools: [], isOrchestrator: true, systemPrompt: 'Eres el responsable de un equipo de RRHH. Lee la solicitud del empleado o manager y decide qué especialista(s) deben ocuparse: dudas de personal (políticas, vacaciones, beneficios), onboarding de nuevas incorporaciones, comunicación interna o temas sensibles de relaciones laborales. Elige solo a los necesarios y reparte el trabajo con instrucciones claras. Escala a la persona de relaciones laborales cualquier caso sensible o confidencial.' },
        { ref: 'people', name: 'People Assistant', emoji: '🤗', role: 'Answers employee questions on policies, leave and benefits', model: M, tools: [], systemPrompt: 'Eres un asistente de RRHH. Respondes dudas de personal sobre políticas, vacaciones, permisos y beneficios con claridad y empatía, citando la política aplicable cuando exista. Si el caso es sensible o requiere excepción, indícalo y sugiere escalarlo en lugar de improvisar una respuesta.' },
        { ref: 'onboarding', name: 'Onboarding Specialist', emoji: '🚀', role: 'Prepares onboarding plans for new hires', model: M, tools: [], systemPrompt: 'Eres especialista en onboarding. A partir del perfil y el puesto de la nueva incorporación, prepara un plan de bienvenida accionable: checklist de primer día, accesos y herramientas necesarias, formación inicial y calendario de las primeras semanas. Sé concreto e incluye responsables cuando sea posible.' },
        { ref: 'comms', name: 'Internal Comms Writer', emoji: '📣', role: 'Drafts internal communications and announcements', model: M, tools: [], systemPrompt: 'Eres redactor de comunicación interna. Redacta anuncios, correos y mensajes para el equipo con un tono claro, cercano y alineado con la cultura de la empresa. Estructura el mensaje con un titular, el contexto, los puntos clave y una llamada a la acción cuando aplique.' },
        { ref: 'relations', name: 'Employee Relations Advisor', emoji: '🤝', role: 'Handles sensitive cases and labor-relations matters', model: M, tools: [], systemPrompt: 'Eres asesor de relaciones laborales. Gestionas casos sensibles: conflictos, quejas, bajas, cumplimiento y situaciones confidenciales. Analiza el caso con prudencia, indica los pasos a seguir y las implicaciones legales o de cumplimiento, y recuerda tratar la información con estricta confidencialidad. No des consejo legal definitivo; recomienda cuándo implicar a legal o a dirección.' },
      ],
      workflow: {
        name: 'HR Team',
        doc: {
          nodes: [
            node('trigger', 'trigger', 40, 285, { event: 'manual' }),
            node('lead', 'router', 340, 285, { agentRef: 'lead', input: 'Lee esta solicitud interna de RRHH y decide qué especialista(s) deben atenderla: dudas de personal (políticas, vacaciones, beneficios), onboarding de nuevas incorporaciones, comunicación interna o temas sensibles/relaciones laborales. Solicitud:\\n{{ticket.summary}}\\n{{ticket.description}}' }),
            node('people', 'agent', 640, 60, { agentRef: 'people', input: 'Responde con claridad y empatía a esta duda de personal, citando la política aplicable si existe:\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('onboarding', 'agent', 640, 210, { agentRef: 'onboarding', input: 'Prepara el plan de onboarding para esta nueva incorporación (checklist, accesos, formación y calendario):\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('comms', 'agent', 640, 360, { agentRef: 'comms', input: 'Redacta la comunicación interna solicitada, con titular, contexto, puntos clave y llamada a la acción:\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('relations', 'agent', 640, 510, { agentRef: 'relations', input: 'Analiza este caso sensible de relaciones laborales con prudencia y confidencialidad, e indica los pasos a seguir:\n{{ticket.summary}}\n{{ticket.description}}' }),
            node('end', 'end', 940, 285, {}),
          ],
          edges: [
            edge('trigger', 'lead'),
            edge('lead', 'people'),
            edge('lead', 'onboarding'),
            edge('lead', 'comms'),
            edge('lead', 'relations'),
            edge('people', 'end'),
            edge('onboarding', 'end'),
            edge('comms', 'end'),
            edge('relations', 'end'),
          ],
          comments: [],
        },
      },
    },
  },

  // ------------------------------ MÁS AGENTS ------------------------------
  {
    id: 'agent-sql-expert',
    kind: 'agent',
    name: 'SQL Expert',
    tagline: 'Escribe y explica consultas SQL en lenguaje natural.',
    description: 'Un experto en SQL: le describes lo que necesitas y te da la consulta, optimizada y explicada. Ideal para analistas y equipos de datos.',
    icon: '🗄️',
    gradient: 'from-sky-500 to-indigo-600',
    category: 'Development',
    difficulty: 'Fácil',
    setupMinutes: 3,
    connectors: [],
    mcps: [],
    tools: ['http'],
    useCases: ['Escribir SQL', 'Optimizar consultas', 'Explicar queries'],
    rating: 4.8,
    installs: 5200,
    author: 'workestra',
    badges: ['Popular', 'Beginner Friendly'],
    collections: ['popular', 'beginner'],
    install: {
      agents: [{ ref: 'a', name: 'SQL Expert', emoji: '🗄️', role: 'SQL', model: M, tools: ['http'], systemPrompt: 'Eres un experto en SQL. A partir de la petición, escribe la consulta correcta y optimizada, y explica brevemente qué hace. Pregunta por el esquema si hace falta.' }],
    },
  },
  {
    id: 'agent-documentation-writer',
    kind: 'agent',
    name: 'Documentation Writer',
    tagline: 'Convierte notas o código en documentación clara.',
    description: 'Un redactor técnico que transforma notas, código o especificaciones en documentación clara y estructurada, lista para tu wiki.',
    icon: '📚',
    gradient: 'from-amber-500 to-yellow-600',
    category: 'Development',
    difficulty: 'Fácil',
    setupMinutes: 3,
    connectors: [],
    mcps: [],
    tools: [],
    useCases: ['Documentación técnica', 'READMEs', 'Guías de uso'],
    rating: 4.6,
    installs: 2400,
    author: 'community',
    badges: ['Beginner Friendly'],
    collections: ['beginner'],
    install: {
      agents: [{ ref: 'a', name: 'Documentation Writer', emoji: '📚', role: 'Documentación', model: M, tools: [], systemPrompt: 'Eres un redactor técnico. Convierte lo que te den (notas, código, specs) en documentación clara, con secciones, ejemplos y un resumen inicial.' }],
    },
  },

  // ------------------------------ MÁS AUTOMATIONS ------------------------------
  {
    id: 'auto-crm-sync',
    kind: 'automation',
    name: 'CRM Synchronization',
    tagline: 'Mantén tu CRM al día automáticamente.',
    description: 'Cuando ocurre un evento (nuevo lead, pago, formulario), actualiza el registro correspondiente en tu CRM y avisa al equipo. Menos copia-pega, datos siempre frescos.',
    icon: '🔄',
    gradient: 'from-violet-500 to-indigo-600',
    category: 'Sales',
    difficulty: 'Media',
    setupMinutes: 8,
    connectors: ['hubspot', 'slack'],
    mcps: [],
    tools: ['http'],
    useCases: ['Sincronizar CRM', 'Actualizar registros', 'Evitar duplicados'],
    rating: 4.5,
    installs: 1700,
    author: 'community',
    badges: ['Sales Automation'],
    collections: ['trending'],
    install: {
      workflow: {
        name: 'CRM Synchronization',
        doc: {
          nodes: [
            node('trigger', 'trigger', 40, 160, { event: 'webhook' }),
            node('prep', 'llm', 300, 160, { model: M, prompt: 'Prepara los campos a actualizar en el CRM a partir del evento.', input: '{{ticket.description}}' }),
            node('note', 'tool', 560, 160, { message: 'Registro sincronizado: {{agent:prep.output}}' }),
            node('end', 'end', 820, 160, {}),
          ],
          edges: [edge('trigger', 'prep'), edge('prep', 'note'), edge('note', 'end')],
          comments: [],
        },
      },
    },
  },

  // ------------------------------ MÁS BROWSER ------------------------------
  {
    id: 'browser-login-website',
    kind: 'browser',
    name: 'Login Website',
    tagline: 'Inicia sesión en una web y realiza una tarea.',
    description: 'Un agente que abre una web, inicia sesión con las credenciales que le des y ejecuta una tarea (descargar, consultar, rellenar). RPA sin scripts.',
    icon: '🔐',
    gradient: 'from-blue-500 to-cyan-600',
    category: 'Operations',
    difficulty: 'Media',
    setupMinutes: 5,
    connectors: [],
    mcps: [],
    tools: ['browser'],
    useCases: ['Portales sin API', 'RPA', 'Tareas repetitivas'],
    variables: [{ key: 'url', label: 'URL de acceso', example: 'https://portal.ejemplo.com/login' }],
    rating: 4.6,
    installs: 1800,
    author: 'workestra',
    badges: ['Browser Automation'],
    collections: ['browser'],
    install: {
      agents: [{ ref: 'a', name: 'Web RPA', emoji: '🔐', role: 'Automatización web', model: M, tools: ['browser'], systemPrompt: 'Abres la web, inicias sesión con las credenciales indicadas y ejecutas la tarea paso a paso. Confirma cada paso y captura si algo falla.' }],
      workflow: {
        name: 'Login Website',
        doc: {
          nodes: [
            node('trigger', 'trigger', 40, 160, { event: 'manual' }),
            node('run', 'agent', 300, 160, { agentRef: 'a', input: 'Inicia sesión y ejecuta:\n{{ticket.description}}' }),
            node('end', 'end', 560, 160, {}),
          ],
          edges: [edge('trigger', 'run'), edge('run', 'end')],
          comments: [],
        },
      },
    },
  },

  // ------------------------------ MÁS MCP ------------------------------
  {
    id: 'mcp-slack-expert',
    kind: 'mcp',
    name: 'Slack Expert',
    tagline: 'Opera Slack por MCP: mensajes, canales y búsquedas.',
    description: 'Un agente que trabaja con tu Slack vía MCP: envía mensajes, resume canales, busca conversaciones y organiza recordatorios, hablando en lenguaje natural.',
    icon: '💬',
    gradient: 'from-purple-500 to-fuchsia-600',
    category: 'Operations',
    difficulty: 'Media',
    setupMinutes: 5,
    connectors: [],
    mcps: ['Slack'],
    tools: [],
    useCases: ['Resumir canales', 'Enviar mensajes', 'Buscar conversaciones'],
    rating: 4.7,
    installs: 1900,
    author: 'workestra',
    badges: ['MCP Ready'],
    collections: ['mcp'],
    install: {
      agents: [{ ref: 'a', name: 'Slack Expert', emoji: '💬', role: 'MCP Slack', model: M, tools: [], mcpServers: [{ name: 'Slack', url: 'https://mcp.slack.com/mcp' }], systemPrompt: 'Eres un experto en Slack. Usa las herramientas MCP para enviar mensajes, resumir canales y buscar conversaciones. Explica lo que haces.' }],
    },
  },
  {
    id: 'mcp-stripe-expert',
    kind: 'mcp',
    name: 'Stripe Expert',
    tagline: 'Consulta pagos y clientes de Stripe por MCP.',
    description: 'Un agente que consulta pagos, suscripciones y clientes de Stripe vía MCP. Pregúntale por los ingresos del mes o el estado de un cobro.',
    icon: '💳',
    gradient: 'from-indigo-500 to-violet-600',
    category: 'Finance',
    difficulty: 'Media',
    setupMinutes: 5,
    connectors: [],
    mcps: ['Stripe'],
    tools: [],
    useCases: ['Consultar pagos', 'Suscripciones', 'Reporting de ingresos'],
    rating: 4.6,
    installs: 1300,
    author: 'workestra',
    badges: ['MCP Ready', 'Enterprise'],
    collections: ['mcp'],
    install: {
      agents: [{ ref: 'a', name: 'Stripe Expert', emoji: '💳', role: 'MCP Stripe', model: M, tools: [], mcpServers: [{ name: 'Stripe', url: 'https://mcp.stripe.com' }], systemPrompt: 'Eres un experto en Stripe. Usa las herramientas MCP para consultar pagos, suscripciones y clientes, y explicar el estado de ingresos y cobros.' }],
    },
  },
];

export const getMarketItem = (id: string): MarketItem | undefined => MARKETPLACE.find((m) => m.id === id);
